name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      # build
      - run: pnpm run build --base /${{github.event.repository.name}}/
