name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # setup
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup

      # build
      - run: pnpm run build --base /$REPO_NAME/
        env:
          REPO_NAME: ${{ github.event.repository.name }}
